# Generated by Django 4.0.5 on 2022-07-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='kg',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
