# Generated by Django 4.0.5 on 2022-07-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_person_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(blank=True, max_length=200, null=True)),
                ('group_of_involved', models.ManyToManyField(related_name='involved', to='base.person')),
                ('owner_of_secret', models.ManyToManyField(related_name='owner', to='base.person')),
            ],
        ),
    ]
