# Generated by Django 4.0.5 on 2022-07-24 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='group_of_involved',
        ),
        migrations.AddField(
            model_name='secret',
            name='group_of_involved',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='involved', to='base.person'),
        ),
        migrations.RemoveField(
            model_name='secret',
            name='owner_of_secret',
        ),
        migrations.AddField(
            model_name='secret',
            name='owner_of_secret',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='base.person'),
        ),
    ]
