# Generated by Django 4.0.5 on 2022-07-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_secret_group_of_involved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='secrets',
        ),
        migrations.AddField(
            model_name='person',
            name='secrets',
            field=models.ManyToManyField(blank=True, null=True, to='base.secret'),
        ),
    ]
