# Generated by Django 4.0.5 on 2022-07-24 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_person_secrets_person_secrets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='secrets',
        ),
        migrations.AddField(
            model_name='secret',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='base.person'),
        ),
        migrations.AddField(
            model_name='secret',
            name='person1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='involved', to='base.person'),
        ),
    ]
