# Generated by Django 4.0.5 on 2022-07-24 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_comment_article_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pinned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('established', models.DateField()),
                ('article', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.article')),
            ],
        ),
    ]
