# Generated by Django 4.0.5 on 2022-07-24 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.archive'),
        ),
    ]
