# Generated by Django 4.0.5 on 2022-07-24 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_archive_article_article_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='articel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.article'),
        ),
    ]
