# Generated by Django 4.0.5 on 2022-07-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_article_comments_comment_articel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article',
            new_name='archive',
        ),
    ]
