# Generated by Django 4.0.5 on 2022-07-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='pdf_file',
            field=models.FileField(upload_to='filesFromUsers'),
        ),
    ]
