# Generated by Django 4.0.5 on 2022-07-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_uploadfile_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadMultipleFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='pdf_file',
            field=models.FileField(upload_to=''),
        ),
    ]
