# Generated by Django 4.0.5 on 2022-07-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_uploadmultiplefiles_alter_uploadfile_pdf_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadMultipleFiles',
        ),
    ]
